name: "ANY network"

options:
  minimumXcodeGenVersion: "2.38.0"
  xcodeVersion: "15.4"
  settings:
    base:
      SWIFT_VERSION: 5.4
      
packages:
  RealmSwift:
    url: https://github.com/realm/realm-swift
    from: "10.52.1"
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    from: "11.10.0"
  Facebook:
    url: https://github.com/facebook/facebook-ios-sdk
    from: "18.0.0"
  XMTPiOS:
    url: https://github.com/xmtp/xmtp-ios.git
    from: "4.2.0"
  KeychainSwift:
    url: https://github.com/evgenyneu/keychain-swift.git
    from: "24.0.0"
  SQLCipherSPM:
    url: https://github.com/chanonly123/SQLCipher-SPM.git
    from: "4.8.0"
    
targets:
  ANY network:
    type: application
    platform: iOS
    name: "ANY network"

    settings:
      base:
        INFOPLIST_FILE: ANY network/Resources/Info.plist
        MARKETING_VERSION: 1 # app version
        CURRENT_PROJECT_VERSION: 32 # build version
        TARGETED_DEVICE_FAMILY: 1 # iPhone
        PRODUCT_BUNDLE_IDENTIFIER: network.any.any
        ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
        DEVELOPMENT_TEAM: 3DV26K7BE7
        GENERATE_INFOPLIST_FILE: NO
        CODE_SIGN_ENTITLEMENTS: ANY network/ANY network.entitlements
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: SQLITE_HAS_CODEC
        OTHER_CFLAGS: -DSQLITE_HAS_CODEC
        OTHER_CPLUSPLUSFLAGS: -DSQLITE_HAS_CODEC
        OTHER_LDFLAGS: -l"xmtpv3"

    deploymentTarget: "17.0"
    sources: ANY network

    dependencies:
      - package: RealmSwift
        embed: true
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseFirestore
      - package: Firebase
        product: FirebaseStorage
      - package: Firebase
        product: FirebaseAnalytics
      - package: Firebase
        product: FirebaseMessaging
      - package: Firebase
        product: FirebaseDynamicLinks
      - package: Facebook
        product: FacebookCore
      - package: Facebook
        product: FacebookLogin
      - package: XMTPiOS
        product: XMTPiOS
      - package: KeychainSwift
        product: KeychainSwift
      - package: SQLCipherSPM
        product: SQLCipher
        

    scheme:
      testTargets:
        - name: ANY networkTests

  ANY networkTests:
    platform: iOS
    type: bundle.unit-test
    sources: ANY networkTests
    name: "ANY networkTests"
    
    dependencies:
      - target: ANY network
    settings:
      base:
        DEVELOPMENT_TEAM: 3DV26K7BE7
        GENERATE_INFOPLIST_FILE: YES
